# Configuration for actions/labeler
# Automatically labels issues based on file paths and patterns

'area: agent':
  - '**/agent/**'
  - '**/src/main/agent/**'

'area: renderer':
  - '**/renderer/**'
  - '**/src/renderer/**'

'area: main':
  - '**/main/**'
  - '**/src/main/**'

'area: storage':
  - '**/storage/**'
  - '**/db/**'

'area: build':
  - '**/electron.vite.config.ts'
  - '**/electron-builder.yml'
  - '**/package.json'
  - '**/tsconfig*.json'

'area: docs':
  - '**/*.md'
  - '**/docs/**'

'area: test':
  - '**/tests/**'
  - '**/test/**'
  - '**/*.test.ts'
  - '**/*.spec.ts'

'area: workflow':
  - '**/.github/**'
