# CodeRabbit AI Configuration for Chaterm
# This file configures CodeRabbit AI to align with project standards

language: en

reviews:
  high_level_summary: true
  review_status: true

  path_filters:
    - '!**/node_modules/**'
    - '!**/dist/**'
    - '!**/out/**'
    - '!**/coverage/**'
    - '!**/*.d.ts'
    - '!**/package-lock.json'
    - '!**/.git/**'
    - '!**/build/**'
    - '!**/playwright-report/**'
    - '!**/test-results/**'

  disable:
    - 'dependencies'
    - 'docker'

  collapse_when_outdated: true
  collapse_when_resolved: true
  max_comments_per_review: 50
  max_files_per_review: 100

chat:
  enabled: true
  auto_reply: false

summaries:
  enabled: true
  bullet_points: true
  diff_summary: true
  section_summary: true

suggestions:
  apply_suggestions_on_merge: false
  auto_apply: false
  min_severity: 'info'

issues:
  validate_linked_issues: true
  identify_related_issues: true

commit_message:
  enabled: true
  min_length: 10
  max_length: 72
  patterns:
    - '^chore:'
    - '^feat:'
    - '^fix:'
    - '^docs:'
    - '^test:'
    - '^refactor:'
    - '^ci:'

ignore:
  - 'formatting'
  - 'whitespace'
  - 'dependency_updates'
  - 'generated_code'
