name: Feature Request
description: Suggest an idea for this project
title: '[FEATURE] '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: what-do-you-want
    attributes:
      label: What do you want?
      description: Describe the feature you'd like and why it would be helpful.
      placeholder: |
        **What:** What feature do you want?
        **Why:** Why would this be useful?
    validations:
      required: true

  - type: textarea
    id: how-should-it-work
    attributes:
      label: How should it work?
      description: Describe how you envision this feature working. (Optional)
      placeholder: How would you like this to work?

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Use cases, examples, mockups, or any other information that might be helpful.
      placeholder: Any additional context, examples, or mockups...
